---
- hosts : 172.31.35.101
  become: yes
  tasks:
  - include_tasks : myfile.yml
  - name : install webserver
    apt:
       name : apache2
       state: present
  - name : copying file
    copy:
        src: mytestfile
        dest: /home/ubuntu

  - name : dwnld file from internet
    ansible.builtin.get_url:
        url : https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
        dest : /home/ubuntu/apache-tomcat-10.0.20.tar.gz
        force_basic_auth: yes

    - name : dwnld dynamic file from internet
    template :
        src : myindexfile.j2
        dest : /var/www/html/index.html
        