---
- hosts: mywebserver
  become: yes
  tasks : 
  - name : i want to install java on ubuntu
    apt :
      name : "{{myjavaonubuntu}}"
      state: present
    when : ansible_os_family=="Debian"

  - name : i want to install java on redhat
    dnf :
      name : "{{myjavaonredhat}}"
      state: present
    when : ansible_os_family=="RedHat"