---
- hosts: mywebserver
  become: yes
  tasks : 
  - name : i want to install webser apache
    apt :
      name : "{{mywebpackonubuntu}}"
      state: present
    when : ansible_os_family=="Debian"

  - name : i want to start webser apache
    service :
      name : "{{mywebpackonubuntu}}"
      state: started
    when : ansible_os_family=="Debian"

  - name : i want to start webser apache
    dnf :
      name : "{{mywebpackouredhat}}"
      state: present
    when : ansible_os_family=="RedHat"

  - name : i want to start webser apache
    service :
      name : "{{mywebpackonredhat}}"
      state: started
    when : ansible_os_family=="RedHat"


  