---
- hosts: all
  become: yes
  tasks : 
  - name : i want to install webser apache
    apt :
      name : apache2
      state: present
  - name : i want to start webser apache
    service :
      name : apache2
      state: started